import Head from 'next/head'
import React, { useState, useEffect } from 'react';
import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import TodoListStyle from '@/styles/TodoListStyle.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { useSelector, useDispatch } from 'react-redux';
import Link from 'next/link';
import {fetchTodos, deleteTodos, setFilter, completeTodos} from '../redux/features/TodoSlice'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dispatch = useDispatch();
  const {todos, loading, filter, stateTriger} = useSelector( state => state.todo )

  useEffect( ()=>{
    if(stateTriger == true){
      dispatch(fetchTodos())
    }
  },[] )
  
  const deleteHandler = (record) => {
    dispatch(deleteTodos(record))
  }

  const CompleteHandler = (record) => {
    const state = {
      name : record.name,
      todoText: record.todoText,
      status: "completed",
      imgUrl:record.imgUrl,
      id: record.id
    }
    dispatch(completeTodos({name:state.name, todoText:state.todoText,status:state.status, imgUrl:state.imgUrl,id:state.id}))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        />
      </Head>
       
      
      <div style={{ height: '100vh', justifyContent: 'center', alignItems: 'center' }}>
    <div className={`${TodoListStyle.bar}`} style={{     textAlign: 'center', margin: '30px' , width: '80%', height:"65px",  margin: '10px auto', textAlign: 'center', borderCollapse: 'collapse', background: 'linear-gradient(to bottom, #0f2027, #203a43, #2c5364)', color: '#fff', fontSize:"20px"}}>
    <button style={{ background: '#fff', color: '#000', padding: '5px 10px', margin: '10px', borderRadius: '5px', cursor: 'pointer' }}>
    <Link href="/AddEditTodos" style={{ color: "#000", textDecoration:"none" }}>Add New Todo</Link>
    </button>
    </div>
      
    {loading ? <div style={{ width: '80%', height:"40px",  margin: '0 auto', textAlign: 'center', borderCollapse: 'collapse', background: '#0f2027', color: '#fff', fontSize:"25px" }}>Please Wait...!</div>  
      :
        <table style={{ width: '80%',  margin: '0 auto', textAlign: 'center', borderCollapse: 'collapse' }} className={`${TodoListStyle.table1}`}>
        <thead>
          <tr className={`${TodoListStyle.tableHeadRow}`} style={{ background: '#0f2027', color: '#fff' }}>
            <th style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.th}`}>Profile</th>
            <th style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.th}`}>Name</th>
            <th style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.th}`}>Todo</th>
            <th style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.th}`}>Status</th>
            <th style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.th}`}>Actions</th>
          </tr>
        </thead>
        <tbody className={`${TodoListStyle.tablebody}`}>
          {todos.filter((item)=>{
            if(filter === "All"){
              return item;
            }else{
              return item.status === filter
            }
          }).map((record, index) => (
            <tr key={index} className={`${TodoListStyle.tableColumn}`}>
              <td style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.td1}`}> <img widtd="70px" height="70px" src={record.imgUrl} /> </td>
              <td style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.td}`}>{record.name}</td>
              <td style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.td}`}>{record.todoText}</td>
              <td style={{ border: '1px solid #ccc', padding: '10px' }} className={`${TodoListStyle.td}`}>{record.status}</td>
              <td style={{ border: '1px solid #ccc' }} className={`${TodoListStyle.td}`}>
              <button style={{ background: '#0f2027', color: '#fff', padding: '5px 10px', margin: '5px', borderRadius: '5px', cursor: 'pointer' }}>
              <Link href={`/${record.id}`} style={{ color: "white", textDecoration:"none" }}>Edit</Link>
              </button>
                <button onClick={()=>deleteHandler(record)} style={{ background: '#0f2027', color: '#fff', padding: '5px 10px', margin: '5px', borderRadius: '5px', cursor: 'pointer' }}  >
                  Delete
                </button>
                <button onClick={()=>CompleteHandler(record)} style={{ background: '#0f2027', color: '#fff', padding: '5px 10px', margin: '5px', borderRadius: '5px', cursor: 'pointer' }}  >
                  Complete
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table> 
      }
    <div style={{     textAlign: 'center', margin: '20px' }}>
    <button style={{ background: '#0f2027', color: '#fff', padding: '5px 10px', margin: '5px', borderRadius: '5px', cursor: 'pointer' }}>
    <Link href="#" style={{ color: "white", textDecoration:"none" }} onClick={ ()=> dispatch(setFilter("All")) }>All</Link>
    </button>
    <button style={{ background: '#0f2027', color: '#fff', padding: '5px 10px', margin: '5px', borderRadius: '5px', cursor: 'pointer' }}>
    <Link href="#" style={{ color: "white", textDecoration:"none" }} onClick={ ()=> dispatch(setFilter("active")) }>Active</Link>
    </button>
    <button style={{ background: '#0f2027', color: '#fff', padding: '5px 10px', margin: '5px', borderRadius: '5px', cursor: 'pointer' }}>
    <Link href="#" style={{ color: "white", textDecoration:"none" }} onClick={ ()=> dispatch(setFilter("inactive")) }>In Active</Link>
    </button>
    </div>
    </div>  

    <br></br>  
    <br></br>  
    <br></br>  
   
    </>
  )
}
